import unittest

from magent.board import Board
from magent.mancala import MancalaEnv
from magent.mcts.mcts import MCTSFactory


class TestBoard(unittest.TestCase):

    def test_mcts_doesnt_mutate_state(self):
        state = MancalaEnv()
        initial_board = Board.clone(state.board)
        mcts = MCTSFactory.test_mcts()
        mcts.search(state)

        self.assertEqual(initial_board.board, state.board.board, "Expect MCTS doesn't mutate the initial board")

    def test_mcts_generate_legal_move(self):
        state = MancalaEnv()
        mcts = MCTSFactory.test_mcts()
        move = mcts.search(state)

        self.assertTrue(state.is_legal(move), "Expect move generated by MCTS is legal move")

    def test_mcts_test_game(self):
        state = MancalaEnv()
        mcts = MCTSFactory.long_test_mcts(sec=600)  # Tweak this to test MCTS manually
        move = mcts.search(state)
        print(move)
